[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
WiSARD = "2b71b7a6-5a26-4a05-9b8d-679d5aa759d4"
